### ISSUE TITLE
Image Depencies in pod 

### ISSUE THREAD

**Issue by nyodas** [blablacar/cnt#24]
2 ways : 
```yaml
pod:
  apps:
    - image: aci/aci
      app:
       ....
      dependencies:
          - deps/deps1
          - deps/deps2
          - deps/deps3
```
or 
```
pod:
  apps:
    - from: 
         - aci/aci1
         - aci/aci2
         - aci/aci3
      app:
       ....
```
